title: Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Hi, I’m Lasse. I’m a sound designer, composer and creative programmer. This is a link to my portfolio.
permalink: ':title/'
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Lasse Heide Fjordbo # add your name
author-img: linkedin_lasse.png # add your photo
about-author: Hi, I’m Lasse. I’m a sound designer, composer and creative programmer with a master degree in audio design. I specialize in sound and music for interactive media such as installations and video games, but I am interested in any project that needs a strong sonic profile. On this site is a selection of projects I have been involved in. If you have an exciting project that needs sound, feel very free to contact me.
 # add description
social-twitter: # add your Twitter handle
social-facebook: 774526841 # add your Facebook handle
social-github: lassehf # add your Github handle
social-linkedin: lasse-heide-fjordbo-779815134 # add your Linkedin handle
social-email: lasseheide@hotmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 9
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
